# Generated by Django 5.2.17 on 2026-09-16 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('draw_type', models.CharField(choices=[('random', 'Random'), ('algorithmic', 'Algorithmic')], default='random', max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('simulated', 'Simulated'), ('published', 'Published')], default='draft', max_length=10)),
                ('winning_numbers', models.JSONField(blank=True, default=list)),
                ('jackpot_rollover_in', models.PositiveIntegerField(default=0)),
                ('jackpot_rollover_out', models.PositiveIntegerField(default=0)),
                ('pool_breakdown', models.JSONField(blank=True, default=dict)),
                ('total_pool', models.PositiveIntegerField(default=0)),
                ('simulated_numbers', models.JSONField(blank=True, default=list)),
                ('simulated_pool', models.PositiveIntegerField(default=0)),
                ('simulated_breakdown', models.JSONField(blank=True, default=dict)),
                ('simulated_rollover_out', models.PositiveIntegerField(default=0)),
                ('simulated_winners', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='WinnerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_count', models.PositiveSmallIntegerField()),
                ('prize_amount', models.PositiveIntegerField(default=0)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='winner_proofs/')),
                ('proof_image_url', models.URLField(blank=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='draws.draw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.JSONField(default=list)),
                ('match_count', models.PositiveSmallIntegerField(default=0)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='draws.draw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('draw', 'user')},
            },
        ),
    ]
